export const SET_TEXT_TO_FILTER = 'SET_TEXT_TO_FILTER';
export const SET_TYPE_TO_FILTER = 'SET_TYPE_TO_FILTER';
export const SET_CATEGORY_TO_FILTER = 'SET_CATEGORY_TO_FILTER';
export const SET_FINAL = 'SET_FINAL';
export const SET_LIST_LENGTH = 'SET_LIST_LENGTH';
export const SET_CAME_FROM_OPTIONS = 'SET_CAME_FROM_OPTIONS';