export const SET_TEXT_TO_FILTER = 'SET_TEXT_TO_FILTER';
export const SET_TYPE_TO_FILTER = 'SET_TYPE_TO_FILTER';
export const SET_CATEGORY_TO_FILTER = 'SET_CATEGORY_TO_FILTER';
export const SET_FINAL = 'SET_FINAL';