export const SET_TEXT_TO_FILTER = 'SET_TEXT_TO_FILTER';
export const SET_TYPE_TO_FILTER = 'SET_TYPE_TO_FILTER';
export const SET_TYPE_TO_FILTER_HEBREW = 'SET_TYPE_TO_FILTER_HEBREW';
export const SET_CATEGORY_TO_FILTER = 'SET_CATEGORY_TO_FILTER';
export const SET_CATEGORY_TO_FILTER_HEBREW = 'SET_CATEGORY_TO_FILTER_HEBREW';
export const SET_FINAL = 'SET_FINAL';
export const SET_FINAL_HEBREW = 'SET_FINAL_HEBREW';